spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      pool-name: DateHikaricp
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    host: 192.168.220.136
    password: 123456
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-wait: 10000ms
        max-active: 8
        min-idle: 5



mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.you.seckill.pojo

logging:
  level:
    com.you.seckill.mapper: debug
